### ISSUE TITLE
Name of repository is not descriptive

### ISSUE THREAD

**Issue by edeno** [bu-cnso/introduction#7]

**Comment by effigies** [comment]
True. git-introduction? introduction-to-git? crash-course-in-git?

**Comment by asoplata** [comment]
can you change git repo names without having to remake the entire repo now?
I thought that wasn't possible

**Comment by effigies** [comment]
![it_would_appear_so](https://cloud.githubusercontent.com/assets/83442/13193522/d3109fe4-d747-11e5-95cc-77d0b5460c84.png)

**Comment by effigies** [comment]
But seriously, yeah. It's nbd. Github will even redirect HTTP requests from the old name to the new one. See: https://github.com/WhisperSystems/TextSecure

**Comment by edeno** [comment]
git-introduction works
